PATH__DIR__VIDEO=/home/laptq/laptq-fs26-shoplifting-detection/data/mendeley/Dataset

TO_USE__YOLOv5_COMPAT=False
PATH__FILE__MODEL=yolov8x-pose.pt
ID__DATA=None
ID__MODEL=yolov8x-pose
ID__TRAIN=None

IMGSZ=640
THRESH__CONF__MIN=0.01
THRESH__IOU=0.45
ID__PREDICT=imgsz-$IMGSZ--conf-$THRESH__CONF__MIN--iou-$THRESH__IOU

DEVICE="cuda:0"
NUM__PAD__0=9

PATH__DIR__LABEL__OUTPUT=/home/laptq/laptq-fs26-shoplifting-detection/outputs/helper--extract--ultralytics--video
POSTFIX__DIR__LABEL__OUTPUT="--PRED--DATA--${ID__DATA}--MODEL--${ID__MODEL}--TRAIN--${ID__TRAIN}--PREDICT--${ID__PREDICT}--JSON"


declare -A MAP__SUBPATH_VIDEO__TO__=(
    # ["Normal/Normal__1_.mp4"]=""
    # ["Normal/Normal__2_.mp4"]=""
    # ["Normal/Normal__3_.mp4"]=""
    # ["Normal/Normal__4_.mp4"]=""
    ["Normal/Normal__5_.mp4"]=""
    # ["Normal/Normal__6_.mp4"]=""
    # ["Normal/Normal__7_.mp4"]=""
    # ["Normal/Normal__8_.mp4"]=""
    # ["Normal/Normal__9_.mp4"]=""
    # ["Normal/Normal__10_.mp4"]=""
    # ["Normal/Normal__11_.mp4"]=""
    # ["Normal/Normal__12_.mp4"]=""
    # ["Normal/Normal__13_.mp4"]=""
    # ["Normal/Normal__14_.mp4"]=""
    # ["Normal/Normal__15_.mp4"]=""
    # ["Normal/Normal__16_.mp4"]=""
    # ["Normal/Normal__17_.mp4"]=""
    # ["Normal/Normal__18_.mp4"]=""
    # ["Normal/Normal__19_.mp4"]=""
    # ["Normal/Normal__20_.mp4"]=""
    # ["Normal/Normal__21_.mp4"]=""
    # ["Normal/Normal__22_.mp4"]=""
    # ["Normal/Normal__23_.mp4"]=""
    # ["Normal/Normal__24_.mp4"]=""
    # ["Normal/Normal__25_.mp4"]=""
    # ["Normal/Normal__26_.mp4"]=""
    # ["Normal/Normal__27_.mp4"]=""
    # ["Normal/Normal__28_.mp4"]=""
    # ["Normal/Normal__29_.mp4"]=""
    # ["Normal/Normal__30_.mp4"]=""
    # ["Normal/Normal__31_.mp4"]=""
    # ["Normal/Normal__32_.mp4"]=""
    # ["Normal/Normal__33_.mp4"]=""
    # ["Normal/Normal__34_.mp4"]=""
    # ["Normal/Normal__35_.mp4"]=""
    # ["Normal/Normal__36_.mp4"]=""
    # ["Normal/Normal__37_.mp4"]=""
    # ["Normal/Normal__38_.mp4"]=""
    # ["Normal/Normal__39_.mp4"]=""
    # ["Normal/Normal__40_.mp4"]=""
    # ["Normal/Normal__41_.mp4"]=""
    # ["Normal/Normal__42_.mp4"]=""
    # ["Normal/Normal__43_.mp4"]=""
    # ["Normal/Normal__44_.mp4"]=""
    # ["Normal/Normal__45_.mp4"]=""
    # ["Normal/Normal__46_.mp4"]=""
    # ["Normal/Normal__47_.mp4"]=""
    # ["Normal/Normal__48_.mp4"]=""
    # ["Normal/Normal__49_.mp4"]=""
    # ["Normal/Normal__50_.mp4"]=""
    # ["Normal/Normal__51_.mp4"]=""
    # ["Normal/Normal__52_.mp4"]=""
    # ["Normal/Normal__53_.mp4"]=""
    # ["Normal/Normal__54_.mp4"]=""
    # ["Normal/Normal__55_.mp4"]=""
    # ["Normal/Normal__56_.mp4"]=""
    # ["Normal/Normal__57_.mp4"]=""
    # ["Normal/Normal__58_.mp4"]=""
    # ["Normal/Normal__59_.mp4"]=""
    # ["Normal/Normal__60_.mp4"]=""
    # ["Normal/Normal__61_.mp4"]=""
    # ["Normal/Normal__62_.mp4"]=""
    # ["Normal/Normal__63_.mp4"]=""
    # ["Normal/Normal__64_.mp4"]=""
    # ["Normal/Normal__65_.mp4"]=""
    # ["Normal/Normal__66_.mp4"]=""
    # ["Normal/Normal__67_.mp4"]=""
    # ["Normal/Normal__68_.mp4"]=""
    # ["Normal/Normal__69_.mp4"]=""
    # ["Normal/Normal__70_.mp4"]=""
    # ["Normal/Normal__71_.mp4"]=""
    # ["Normal/Normal__72_.mp4"]=""
    # ["Normal/Normal__73_.mp4"]=""
    # ["Normal/Normal__74_.mp4"]=""
    # ["Normal/Normal__75_.mp4"]=""
    # ["Normal/Normal__76_.mp4"]=""
    # ["Normal/Normal__77_.mp4"]=""
    # ["Normal/Normal__78_.mp4"]=""
    # ["Normal/Normal__79_.mp4"]=""
    # ["Normal/Normal__80_.mp4"]=""
    # ["Normal/Normal__81_.mp4"]=""
    # ["Normal/Normal__82_.mp4"]=""
    # ["Normal/Normal__83_.mp4"]=""
    # ["Normal/Normal__84_.mp4"]=""
    # ["Normal/Normal__85_.mp4"]=""
    # ["Normal/Normal__86_.mp4"]=""
    # ["Normal/Normal__87_.mp4"]=""
    # ["Normal/Normal__88_.mp4"]=""
    # ["Normal/Normal__89_.mp4"]=""
    # ["Normal/Normal__90_.mp4"]=""

    # ["Shoplifting/Shoplifting__1_.mp4"]=""
    # ["Shoplifting/Shoplifting__2_.mp4"]=""
    # ["Shoplifting/Shoplifting__3_.mp4"]=""
    # ["Shoplifting/Shoplifting__4_.mp4"]=""
    # ["Shoplifting/Shoplifting__5_.mp4"]=""
    # ["Shoplifting/Shoplifting__6_.mp4"]=""
    # ["Shoplifting/Shoplifting__7_.mp4"]=""
    # ["Shoplifting/Shoplifting__8_.mp4"]=""
    # ["Shoplifting/Shoplifting__9_.mp4"]=""
    # ["Shoplifting/Shoplifting__10_.mp4"]=""
    # ["Shoplifting/Shoplifting__11_.mp4"]=""
    # ["Shoplifting/Shoplifting__12_.mp4"]=""
    # ["Shoplifting/Shoplifting__13_.mp4"]=""
    # ["Shoplifting/Shoplifting__14_.mp4"]=""
    # ["Shoplifting/Shoplifting__15_.mp4"]=""
    # ["Shoplifting/Shoplifting__16_.mp4"]=""
    # ["Shoplifting/Shoplifting__17_.mp4"]=""
    # ["Shoplifting/Shoplifting__18_.mp4"]=""
    # ["Shoplifting/Shoplifting__19_.mp4"]=""
    # ["Shoplifting/Shoplifting__20_.mp4"]=""
    # ["Shoplifting/Shoplifting__21_.mp4"]=""
    # ["Shoplifting/Shoplifting__22_.mp4"]=""
    # ["Shoplifting/Shoplifting__23_.mp4"]=""
    # ["Shoplifting/Shoplifting__24_.mp4"]=""
    # ["Shoplifting/Shoplifting__25_.mp4"]=""
    # ["Shoplifting/Shoplifting__26_.mp4"]=""
    # ["Shoplifting/Shoplifting__27_.mp4"]=""
    # ["Shoplifting/Shoplifting__28_.mp4"]=""
    # ["Shoplifting/Shoplifting__29_.mp4"]=""
    # ["Shoplifting/Shoplifting__30_.mp4"]=""
    # ["Shoplifting/Shoplifting__31_.mp4"]=""
    # ["Shoplifting/Shoplifting__32_.mp4"]=""
    # ["Shoplifting/Shoplifting__33_.mp4"]=""
    # ["Shoplifting/Shoplifting__34_.mp4"]=""
    # ["Shoplifting/Shoplifting__35_.mp4"]=""
    # ["Shoplifting/Shoplifting__36_.mp4"]=""
    # ["Shoplifting/Shoplifting__37_.mp4"]=""
    # ["Shoplifting/Shoplifting__38_.mp4"]=""
    # ["Shoplifting/Shoplifting__39_.mp4"]=""
    # ["Shoplifting/Shoplifting__40_.mp4"]=""
    # ["Shoplifting/Shoplifting__41_.mp4"]=""
    # ["Shoplifting/Shoplifting__42_.mp4"]=""
    # ["Shoplifting/Shoplifting__43_.mp4"]=""
    # ["Shoplifting/Shoplifting__44_.mp4"]=""
    # ["Shoplifting/Shoplifting__45_.mp4"]=""
    # ["Shoplifting/Shoplifting__46_.mp4"]=""
    # ["Shoplifting/Shoplifting__47_.mp4"]=""
    # ["Shoplifting/Shoplifting__48_.mp4"]=""
    # ["Shoplifting/Shoplifting__49_.mp4"]=""
    # ["Shoplifting/Shoplifting__50_.mp4"]=""
    # ["Shoplifting/Shoplifting__51_.mp4"]=""
    # ["Shoplifting/Shoplifting__52_.mp4"]=""
    # ["Shoplifting/Shoplifting__53_.mp4"]=""
    # ["Shoplifting/Shoplifting__54_.mp4"]=""
    # ["Shoplifting/Shoplifting__55_.mp4"]=""
    # ["Shoplifting/Shoplifting__56_.mp4"]=""
    # ["Shoplifting/Shoplifting__57_.mp4"]=""
    # ["Shoplifting/Shoplifting__58_.mp4"]=""
    # ["Shoplifting/Shoplifting__59_.mp4"]=""
    # ["Shoplifting/Shoplifting__60_.mp4"]=""
    # ["Shoplifting/Shoplifting__61_.mp4"]=""
    # ["Shoplifting/Shoplifting__62_.mp4"]=""
    # ["Shoplifting/Shoplifting__63_.mp4"]=""
    # ["Shoplifting/Shoplifting__64_.mp4"]=""
    # ["Shoplifting/Shoplifting__65_.mp4"]=""
    # ["Shoplifting/Shoplifting__66_.mp4"]=""
    # ["Shoplifting/Shoplifting__67_.mp4"]=""
    # ["Shoplifting/Shoplifting__68_.mp4"]=""
    # ["Shoplifting/Shoplifting__69_.mp4"]=""
    # ["Shoplifting/Shoplifting__70_.mp4"]=""
    # ["Shoplifting/Shoplifting__71_.mp4"]=""
    # ["Shoplifting/Shoplifting__72_.mp4"]=""
    # ["Shoplifting/Shoplifting__73_.mp4"]=""
    # ["Shoplifting/Shoplifting__74_.mp4"]=""
    # ["Shoplifting/Shoplifting__75_.mp4"]=""
    # ["Shoplifting/Shoplifting__76_.mp4"]=""
    # ["Shoplifting/Shoplifting__77_.mp4"]=""
    # ["Shoplifting/Shoplifting__78_.mp4"]=""
    # ["Shoplifting/Shoplifting__79_.mp4"]=""
    # ["Shoplifting/Shoplifting__80_.mp4"]=""
    # ["Shoplifting/Shoplifting__81_.mp4"]=""
    # ["Shoplifting/Shoplifting__82_.mp4"]=""
    # ["Shoplifting/Shoplifting__83_.mp4"]=""
    # ["Shoplifting/Shoplifting__84_.mp4"]=""
    # ["Shoplifting/Shoplifting__85_.mp4"]=""
    # ["Shoplifting/Shoplifting__86_.mp4"]=""
    # ["Shoplifting/Shoplifting__87_.mp4"]=""
    # ["Shoplifting/Shoplifting__88_.mp4"]=""
    # ["Shoplifting/Shoplifting__89_.mp4"]=""
    # ["Shoplifting/Shoplifting__90_.mp4"]=""
    # ["Shoplifting/Shoplifting__91_.mp4"]=""
    # ["Shoplifting/Shoplifting__92_.mp4"]=""
    # ["Shoplifting/Shoplifting__93_.mp4"]=""
)

IFS=$'\n'
TAG__FAILED="\033[31m[FAILED]\033[0m"
TAG__PASSED="\033[92m[PASSED]\033[0m"
TAG__INFO="\033[94m[INFO]\033[0m"
TAG__WARNING="\033[33m[WARNING]\033[0m"


for subpath__video in "${!MAP__SUBPATH_VIDEO__TO__[@]}"; do
    path__file__input="${PATH__DIR__VIDEO}/${subpath__video}"
    path__dir__lbl__output="${PATH__DIR__LABEL__OUTPUT}/${subpath__video}/labels${POSTFIX__DIR__LABEL__OUTPUT}"

    [[ -d "${path__dir__lbl__output}" ]] && rm -r "${path__dir__lbl__output}"
    mkdir -p "${path__dir__lbl__output}"

    python3 submodules/laptq_utils/main.py \
        helper__extract__ultralytics__video \
        --path__file__input "${path__file__input}" \
        --path__dir__lbl__output "${path__dir__lbl__output}" \
        --path__file__model "${PATH__FILE__MODEL}" \
        --device $DEVICE \
        --imgsz $IMGSZ \
        --thresh__conf__min $THRESH__CONF__MIN \
        --thresh__iou $THRESH__IOU \
        --to_save__img False \
        --num__pad__0 $NUM__PAD__0 \
        --to_use__yolov5_compat $TO_USE__YOLOv5_COMPAT \
        --task pose \
        --list__name_keypoints "['nose', 'left_eye', 'right_eye', 'left_ear', 'right_ear', 'left_shoulder', 'right_shoulder', 'left_elbow', 'right_elbow', 'left_wrist', 'right_wrist', 'left_hip', 'right_hip', 'left_knee', 'right_knee', 'left_ankle', 'right_ankle']" \

    echo -e "${TAG__INFO} Done: ${subpath__video}"
        
done